const Features = {
  'JACKAL_HOLIDAYS': {
    edc: ['DU', 'DU2'],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: true,
    isAds: false,
    isVirtualAccount: true,
    isRoundedTrip: false,
    isMember: false,
    isPrintFromApi: false // Print Data From API (no need to remodel)
  },
  'DAYTRANS': {
    edc: ['91', '36', '17', '71', '25'],
    isInsurance: true,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: false,
    isAds: false,
    isVirtualAccount: false,
    isRoundedTrip: false,
    isMember: false,
    isPrintFromApi: false
  },
  'BARAYA': {
    edc: ['BBB', 'BSP1', 'BSP2', 'BOS2'],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: true,
    isChangeDeparturePool: true,
    useV2: false,
    isAds: false,
    isVirtualAccount: false,
    isRoundedTrip: false,
    isMember: false,
    isPrintFromApi: false
  },
  'BTM': {
    edc: [],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: true,
    isAds: false,
    isVirtualAccount: true,
    isRoundedTrip: false,
    isMember: false,
    isPrintFromApi: false
  },
  'ARAGON': {
    edc: [],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: false,
    isAds: false,
    isVirtualAccount: false,
    isRoundedTrip: false,
    isMember: false,
    isPrintFromApi: false
  },
  'KRUZZ': {
    edc: [],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: true,
    isAds: false,
    isVirtualAccount: true,
    isRoundedTrip: false,
    isMember: false,
    isPrintFromApi: false
  },
  'CONNEX': {
    edc: ['MCAF'],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: true,
    useV2: true,
    isAds: false,
    isVirtualAccount: true,
    isRoundedTrip: true,
    isMember: true,
    isPrintFromApi: false
  },
  'RAPUTRI': {
    edc: [],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: true,
    isAds: false,
    isVirtualAccount: true,
    isRoundedTrip: true,
    isMember: false,
    isPrintFromApi: false
  },
  'ASMAT': {
    edc: ['BBB'],
    isInsurance: false,
    isBoarding: true,
    isVoucher: true,
    isPrintTicket: false,
    isChangeDeparturePool: false,
    useV2: true,
    isAds: true,
    isVirtualAccount: true,
    isRoundedTrip: true,
    isMember: false,
    isPrintFromApi: false
  },
};

export default Features;